#!/usr/bin/env python3
"""Emit a C file holding a PRX's bytes: the EBOOT carries the Media Engine
kernel helper and writes it to its data/ folder at boot (src/port/psp/me.c),
so a release is the EBOOT alone.  usage: embed_prx.py in.prx out.c"""
import sys
data = open(sys.argv[1], "rb").read()
with open(sys.argv[2], "w") as f:
    f.write("/* generated by tools/psp/embed_prx.py from %s */\n" % sys.argv[1])
    f.write("const unsigned int gPortMeKprxSize = %du;\n" % len(data))
    f.write("const unsigned char gPortMeKprx[%d] __attribute__((aligned(16))) = {\n" % len(data))
    for i in range(0, len(data), 16):
        f.write("    " + ",".join("0x%02x" % b for b in data[i:i + 16]) + ",\n")
    f.write("};\n")
