#!/usr/bin/env python3
"""Generate the segment translation tables for the PSP port.

The game refers to a lot of data by N64 segmented address (0x07001350 = the
course display list that lives 0x1350 bytes into segment 7).  The decomp names
those objects after their segment offset (d_course_<c>_packed_dl_1350,
D_0D001200, ...) and torch records offsets in yamls/us/*.yml, so the mapping
offset -> symbol can be generated.  At run time src/port/segments.c resolves a
segmented address by binary-searching these tables.

Output: a C file (argument 1).  Run from the repository root.
"""
import os
import re
import sys

# Same order as the COURSES enum in include/course.h / gCourseTable.
COURSES = [
    "mario_raceway", "choco_mountain", "bowsers_castle", "banshee_boardwalk",
    "yoshi_valley", "frappe_snowland", "koopa_troopa_beach", "royal_raceway",
    "luigi_raceway", "moo_moo_farm", "toads_turnpike", "kalimari_desert",
    "sherbet_land", "rainbow_road", "wario_stadium", "block_fort", "skyscraper",
    "double_deck", "dks_jungle_parkway", "big_donut",
]

EXTERN_RE = re.compile(r"^extern\s+[A-Za-z_0-9 ]+?\s*\*?\s*([A-Za-z_0-9]+)\[\]", re.M)


def symbols_with_offsets(header, seg_hint):
    """(offset, symbol) for every extern whose name carries its offset."""
    out = []
    with open(header) as f:
        text = f.read()
    for name in EXTERN_RE.findall(text):
        m = re.search(r"_dl_([0-9A-Fa-f]+)$", name)
        if m:
            out.append((int(m.group(1), 16), name))
            continue
        m = re.search(r"_0([0-9A-Fa-f])([0-9A-Fa-f]{6})$", name)
        if m and int(m.group(1), 16) == seg_hint:
            out.append((int(m.group(2), 16), name))
    return out


def symbols_from_yaml(path):
    """(offset, symbol) from a torch yaml (no PyYAML dependency)."""
    out = []
    symbol = None
    offset = None
    in_tables = False
    with open(path) as f:
        for raw in f:
            line = raw.rstrip("\n")
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            indent = len(line) - len(line.lstrip(" "))
            if indent == 0:
                if symbol and offset is not None:
                    out.append((offset, symbol))
                symbol, offset = None, None
                in_tables = False
                continue
            if stripped.startswith("tables:"):
                in_tables = True
                continue
            if in_tables:
                m = re.match(r"([A-Za-z_0-9]+):\s*$", stripped)
                if m and indent == 4:
                    symbol = m.group(1)
                    offset = None
                m = re.match(r"range:\s*\[\s*(0x[0-9A-Fa-f]+)", stripped)
                if m and symbol:
                    out.append((int(m.group(1), 16), symbol))
                    symbol, offset = None, None
                continue
            m = re.match(r"symbol:\s*([A-Za-z_0-9]+)", stripped)
            if m:
                symbol = m.group(1)
            m = re.match(r"offset:\s*(0x[0-9A-Fa-f]+)", stripped)
            if m:
                offset = int(m.group(1), 16)
    if symbol and offset is not None:
        out.append((offset, symbol))
    return out


def declared_symbols(header):
    with open(header) as f:
        return set(re.findall(r"\b([A-Za-z_][A-Za-z_0-9]*)\s*\[", f.read()))


def emit_table(lines, cname, entries, declared=None):
    entries = [(e[0] & 0xFFFFFF, e[1]) for e in entries if re.match(r"[A-Za-z_]", e[1])]
    if declared is not None:
        entries = [e for e in entries if e[1] in declared]
    entries = sorted(set(entries))
    if not entries:
        lines.append(f"static const PortSegEntry {cname}[1] = {{ {{ 0, 0, NULL }} }};")
        lines.append(f"#define {cname}_count 0")
        return
    lines.append(f"static const PortSegEntry {cname}[] = {{")
    for i, (off, sym) in enumerate(entries):
        end = entries[i + 1][0] if i + 1 < len(entries) else 0x1000000
        lines.append(f"    {{ 0x{off:06X}, 0x{end - off:06X}, (const void*) &{sym} }},")
    lines.append("};")
    lines.append(f"#define {cname}_count {len(entries)}")


def main():
    out_path = sys.argv[1]
    lines = [
        "/* Generated by tools/psp/gen_seg_tables.py - do not edit. */",
        "#include <ultra64.h>",
        "#include <macros.h>",
        "#include <common_structs.h>",
        "#include <course.h>",
        "#include <assets/common_data.h>",
        "#include <assets/ceremony_data.h>",
        "#include <assets/startup_logo.h>",
        '#include "port.h"',
    ]
    for c in COURSES:
        lines.append(f'#include "courses/{c}/course_data.h"')
        lines.append(f'#include "courses/{c}/course_displaylists.inc.h"')
    lines.append("")

    for c in COURSES:
        emit_table(lines, f"seg6_{c}", symbols_with_offsets(f"courses/{c}/course_data.h", 6))
        emit_table(lines, f"seg7_{c}", symbols_with_offsets(f"courses/{c}/course_displaylists.inc.h", 7))
        lines.append("")

    lines.append("const PortCourseSegTables gPortCourseSegTables[] = {")
    for c in COURSES:
        lines.append(f"    {{ {{ seg6_{c}, seg6_{c}_count }}, {{ seg7_{c}, seg7_{c}_count }} }},")
    lines.append("    { { NULL, 0 }, { NULL, 0 } }, /* award ceremony */")
    lines.append("};")
    lines.append("")

    for cname, yml, src, var in [
        ("segD_common", "yamls/us/common_data.yml", "assets/code/common_data/common_data.c", "gPortCommonDataSegTable"),
        ("segB_ceremony", "yamls/us/ceremony_data.yml", "assets/code/ceremony_data/ceremony_data.c", "gPortCeremonyDataSegTable"),
        ("seg6_logo", "yamls/us/startup_logo.yml", "assets/code/startup_logo/startup_logo.c", "gPortStartupLogoSegTable"),
    ]:
        # Only symbols torch actually defines (yaml entries in APPEND mode are
        # folded into a parent array and have no symbol of their own).
        emit_table(lines, cname, symbols_from_yaml(yml), declared_symbols(src))
        lines.append(f"const PortSegTable {var} = {{ {cname}, {cname}_count }};")
        lines.append("")

    # The N64 build's ROM-segment symbols for courses (mio0 blobs) and the
    # packed display-list blobs are never read on the PSP (the course C sources
    # are linked in directly), but gCourseTable still names them.
    for c in COURSES:
        for s in ["dl_mio0SegmentRomStart", "dl_mio0SegmentRomEnd", "offsetsSegmentRomStart", "offsetsSegmentRomEnd"]:
            lines.append(f"u8 _course_{c}_{s}[1];")
        for s in ["vertexSegmentRomStart", "vertexSegmentRomEnd"]:
            lines.append(f"u8 _{c}_{s}[1];")
        lines.append(f"u8 d_course_{c}_packed[1];")
    lines.append("")

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
