#!/usr/bin/env python3
"""Generate courses/<course>/course_textures.linkonly.h for the PSP port.

The N64 build links each course's display lists against a "linkonly" object
whose texture symbols sit at segment-5 addresses (0x05000000 + running offset
of the decompressed textures, in the order listed in course_offsets.c).  At
run time decompress_textures() unpacks the mio0 textures in that same order,
so the display lists' texture pointers resolve through segment 5.

The port keeps that scheme but does not need a link trick: the symbols are
plain #defines to the segmented address.  Offsets follow MIO0_0F(): each
texture occupies ALIGN16(data_size) bytes.

usage: gen_course_textures.py <course_name> [<course_name> ...]
"""
import re
import sys

sys.path.insert(0, "tools")
from linkonly_generator_tables import abbreviations  # noqa: E402

TEXTURE_RE = re.compile(r"{\s*(\S+),\s+(\S+),\s+(\S+),\s+\S+\s*}")


def align16(v):
    return (v + 0xF) & ~0xF


def generate(course):
    with open(f"courses/{course}/course_offsets.c") as f:
        textures = TEXTURE_RE.findall(f.read())
    if not textures:
        raise SystemExit(f"no texture entries in courses/{course}/course_offsets.c")

    lines = [
        "/* Generated by tools/psp/gen_course_textures.py - do not edit. */",
        "#ifndef COURSE_TEXTURES_H",
        "#define COURSE_TEXTURES_H",
        "",
        "#include <PR/ultratypes.h>",
        "",
    ]
    offset = 0
    for name, _file_size, data_size in textures:
        if name == "0x00000000":
            continue
        unique = re.sub("gTexture", f"g{abbreviations[course]}Texture", name)
        lines.append(f"#define {unique} ((u8*) 0x{0x05000000 + offset:08X})")
        offset += align16(int(data_size, 16))
    lines += ["", "#endif", ""]

    with open(f"courses/{course}/course_textures.linkonly.h", "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    for c in sys.argv[1:]:
        generate(c)
