#!/usr/bin/env python3
"""Emit port_build_id.c: a 16-bit id of this build's code objects.

Ad hoc play is input lockstep: every console must run the same simulation, so
consoles on different builds must not join each other.  Every packet carries
this id (src/port/net/lockstep.c) and a packet from another build is refused.
The id is a hash of the object files, so it changes whenever the code does and
nobody has to remember to bump a number.

usage: gen_build_id.py out.c obj...
"""
import hashlib
import sys

out, objs = sys.argv[1], sorted(sys.argv[2:])
h = hashlib.sha1()
for path in objs:
    with open(path, "rb") as f:
        h.update(f.read())
build_id = int.from_bytes(h.digest()[:2], "big") or 1  # 0 is what builds before the id send
with open(out, "w") as f:
    f.write("/* generated by tools/psp/gen_build_id.py */\n")
    f.write("const unsigned short gPortBuildId = 0x%04X;\n" % build_id)
